common: &default_settings
  license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  app_name: <%= ENV.fetch("NEW_RELIC_APP_NAME", "MiGarden") %>

  monitor_mode: true
  log_level: info

  distributed_tracing:
    enabled: true

  application_logging:
    enabled: true
    forwarding:
      enabled: true
      max_samples_stored: 1000
    local_decorating:
      enabled: true

development:
  <<: *default_settings
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true